# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Dot < Formula
  desc "The dotfiles manager"
  homepage "https://github.com/fschrhunt/dot"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/dot/releases/download/v1.0.0/dot_v1.0.0_darwin_arm64.tar.gz"
      sha256 "6bd80c8ffa758693c6983f76d15f7d59d54d39d4860c2e40a7e30ef8309e8de1"
    end
    on_intel do
      url "https://github.com/fschrhunt/dot/releases/download/v1.0.0/dot_v1.0.0_darwin_amd64.tar.gz"
      sha256 "336e77b42baef8cec4142d077fa3daac2dd8a50c9c0b8a85eaa213b2ef45411c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/dot/releases/download/v1.0.0/dot_v1.0.0_linux_arm64.tar.gz"
      sha256 "c7466c94f725b2972ac9e6d64bc0b3aac2293b668b34731acb13e199f8b0df8b"
    end
    on_intel do
      url "https://github.com/fschrhunt/dot/releases/download/v1.0.0/dot_v1.0.0_linux_amd64.tar.gz"
      sha256 "fd627d1e08d6e58b41f9cb9b8ebdfa0fa055da2a3a8f595360104cd345ec3fd6"
    end
  end

  def install
    bin.install "dot"
  end

  def caveats
    <<~EOS
      Next: dot init
    EOS
  end

  test do
    assert_equal "v1.0.0", shell_output("#{bin}/dot --version").strip
  end
end
